// Scene templates
export const PREDEFINED_SCENES = {
  fantasy_dungeon: {
    name: "Fantasy Dungeon",
    data: {
      background: {
        src: "modules/foundry-landing/assets/images/A_fantasy_adventure-themed_background_image_design_taller.png",
        tint: "#ffffff",
        anchorX: 0,
        anchorY: 0,
        offsetX: 0,
        offsetY: 0,
        fit: "fill",
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        alphaThreshold: 0,
      },
      thumb:
        "modules/foundry-landing/assets/images/A_fantasy_adventure-themed_background_image_design_taller.png",
      environment: {
        globalLight: {
          enabled: true,
          darkness: {
            max: 1,
            min: 0,
          },
          alpha: 0.5,
          bright: false,
          color: null,
          coloration: 1,
          luminosity: 0,
          saturation: 0,
          contrast: 0,
          shadows: 0,
        },
        darknessLevel: 1,
        darknessLock: false,
        cycle: true,
        base: {
          hue: 0,
          intensity: 0,
          luminosity: 0,
          saturation: 0,
          shadows: 0,
        },
        dark: {
          hue: 0.7138888888888889,
          intensity: 0,
          luminosity: -0.25,
          saturation: 0,
          shadows: 0,
        },
      },
      lights: [
        {
          _id: "CuNvyxWmFTiiMjt9",
          x: 1062,
          y: 201,
          elevation: 0,
          rotation: 0,
          walls: true,
          vision: false,
          config: {
            negative: false,
            priority: 0,
            alpha: 0.45,
            angle: 360,
            bright: 12.39,
            color: null,
            coloration: 1,
            dim: 24.77,
            attenuation: 0.5,
            luminosity: 0.5,
            saturation: 0,
            contrast: 0,
            shadows: 0,
            animation: {
              type: "torch",
              speed: 2,
              intensity: 3,
              reverse: false,
            },
            darkness: {
              min: 0,
              max: 1,
            },
          },
          hidden: false,
          flags: {},
        },
        {
          x: 1432,
          y: 210,
          elevation: 0,
          rotation: 0,
          walls: true,
          vision: false,
          config: {
            negative: false,
            priority: 0,
            alpha: 0.45,
            angle: 360,
            bright: 12.39,
            color: null,
            coloration: 1,
            dim: 24.77,
            attenuation: 0.5,
            luminosity: 0.5,
            saturation: 0,
            contrast: 0,
            shadows: 0,
            animation: {
              type: "torch",
              speed: 3,
              intensity: 2,
              reverse: false,
            },
            darkness: {
              min: 0,
              max: 1,
            },
          },
          hidden: false,
          flags: {},
          _id: "KlCrKMw4CwLaxTb7",
        },
        {
          x: 1719,
          y: 200,
          elevation: 0,
          rotation: 0,
          walls: true,
          vision: false,
          config: {
            negative: false,
            priority: 0,
            alpha: 0.45,
            angle: 360,
            bright: 12.39,
            color: null,
            coloration: 1,
            dim: 24.77,
            attenuation: 0.5,
            luminosity: 0.5,
            saturation: 0,
            contrast: 0,
            shadows: 0,
            animation: {
              type: "torch",
              speed: 1,
              intensity: 4,
              reverse: false,
            },
            darkness: {
              min: 0,
              max: 1,
            },
          },
          hidden: false,
          flags: {},
          _id: "Eu2Om8SKqVjh8sf5",
        },
        {
          _id: "2pGppyLtbXCw5qnU",
          x: 1504,
          y: 49,
          elevation: 0,
          rotation: 0,
          walls: true,
          vision: false,
          config: {
            negative: false,
            priority: 0,
            alpha: 0.5,
            angle: 360,
            bright: 51.37,
            color: null,
            coloration: 1,
            dim: 102.75,
            attenuation: 0.5,
            luminosity: 0.5,
            saturation: 0,
            contrast: 0,
            shadows: 0,
            animation: {
              type: "fog",
              speed: 4,
              intensity: 2,
              reverse: false,
            },
            darkness: {
              min: 0,
              max: 1,
            },
          },
          hidden: false,
          flags: {},
        },
      ],
      foreground: null,
      foregroundElevation: 4,
      tokenVision: false,
      backgroundColor: "#000000",
      grid: {
        type: 0,
        size: 100,
        style: "solidLines",
        thickness: 1,
        color: "#000000",
        alpha: 0.2,
        distance: 5,
        units: "",
      },
      initial: {
        x: 1811,
        y: 1143,
        scale: 0.3333333333333333,
      },
      width: 3584,
      height: 2304,
      fog: {
        exploration: true,
        overlay: null,
        colors: {
          explored: null,
          unexplored: null,
        },
      },
      flags: {
        "foundry-landing": {
          isResponsive: true,
          originalWidth: 3584,
          originalHeight: 2304,
        },
        pf2e: {
          rulesBasedVision: null,
          hearingRange: null,
          environmentTypes: [],
        },
      },
      _id: "x6pE2Mdh8KOdLMQw",
      navigation: true,
      navOrder: 0,
      navName: "",
      drawings: [],
      tokens: [],
      notes: [],
      sounds: [],
      regions: [],
      templates: [],
      tiles: [],
      walls: [],
      playlist: null,
      playlistSound: null,
      journal: null,
      journalEntryPage: null,
      weather: "",
      folder: null,
      sort: 0,
      ownership: {
        default: 0,
        LD1vixuhr1BrLSVV: 3,
      },
      _stats: {
        compendiumSource: null,
        duplicateSource: null,
        coreVersion: "12.331",
        systemId: "pf2e",
        systemVersion: "6.9.0",
        createdTime: 1743908167746,
        modifiedTime: 1743908526642,
        lastModifiedBy: "b08BQYQhN1VcqF2s",
      },
    },
  },
  // Add more predefined scenes here in the future
};
